name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: scripts/build-dist.sh
      - uses: actions/upload-artifact@v2
        with:
          name: rp6l-linux
          path: dist/
      - run: docker build --tag rp6l --target final .
